#if os(iOS) || os(visionOS)
@preconcurrency import SwiftTerm
import UIKit

struct TerminalColorSet {
    let ansiRGB: [(r: UInt8, g: UInt8, b: UInt8)]
    let foreground: UIColor
    let background: UIColor
    let cursor: UIColor
}

extension TerminalColorSet {
    func apply(to view: TerminalView) {
        let terminal = view.getTerminal()

        // Temporarily disconnect the terminal delegate so that OSC response
        // bytes generated by SwiftTerm don't flow through our send path
        // into the remote PTY (where the shell echoes them as text garbage
        // like "65;4;1;2;6;21;22;17;28c65;20;1c").
        let savedDelegate = view.terminalDelegate
        view.terminalDelegate = nil

        for (i, rgb) in ansiRGB.prefix(16).enumerated() {
            let seq = "\u{1b}]4;\(i);rgb:\(hex2(rgb.r))/\(hex2(rgb.g))/\(hex2(rgb.b))\u{1b}\\"
            terminal.feed(text: seq)
        }

        func osc(_ code: Int, _ color: UIColor) {
            var r: CGFloat = 0, g: CGFloat = 0, b: CGFloat = 0
            color.getRed(&r, green: &g, blue: &b, alpha: nil)
            let seq = "\u{1b}]\(code);rgb:\(hex2f(r))/\(hex2f(g))/\(hex2f(b))\u{1b}\\"
            terminal.feed(text: seq)
        }
        osc(10, foreground)
        osc(11, background)
        osc(12, cursor)

        // Restore the delegate so normal terminal I/O resumes.
        view.terminalDelegate = savedDelegate

        view.nativeForegroundColor = foreground
        view.nativeBackgroundColor = background
        view.backgroundColor = background
        view.caretColor = cursor
    }
}

private func hex2(_ v: UInt8) -> String {
    String(format: "%02x", v)
}

private func hex2f(_ v: CGFloat) -> String {
    String(format: "%02x", Int(v * 255))
}
#endif
